# Generated by Django 5.2.7 on 2025-10-15 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrushingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, unique=True, verbose_name='machine ID')),
                ('name', models.CharField(max_length=100, verbose_name='machine name')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='manufacturer')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='installation date')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline'), ('error', 'Error')], default='operational', max_length=20, verbose_name='status')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='last maintenance')),
                ('next_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='next maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('optimal_pressure', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='optimal pressure (bar)')),
                ('optimal_temperature', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='optimal temperature (°C)')),
                ('optimal_rotation_speed', models.DecimalField(decimal_places=2, default=15.0, max_digits=6, verbose_name='optimal rotation speed (RPM)')),
            ],
            options={
                'verbose_name': 'crushing machine',
                'verbose_name_plural': 'crushing machines',
                'ordering': ['machine_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='stage name')),
                ('stage_type', models.CharField(choices=[('harvesting', 'Harvesting'), ('cleaning', 'Cleaning'), ('crushing', 'Crushing'), ('juice_extraction', 'Juice Extraction'), ('clarification', 'Clarification'), ('evaporation', 'Evaporation'), ('crystallization', 'Crystallization'), ('centrifugation', 'Centrifugation'), ('drying', 'Drying'), ('packaging', 'Packaging')], max_length=20, unique=True, verbose_name='stage type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('standard_duration', models.DurationField(blank=True, help_text='Expected duration for this stage (HH:MM:SS)', null=True, verbose_name='standard duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'production stage',
                'verbose_name_plural': 'production stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='batch number')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='expected yield (kg)')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='actual yield (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='farms.farm', verbose_name='source farm')),
            ],
            options={
                'verbose_name': 'production batch',
                'verbose_name_plural': 'production batches',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('raw_juice', 'Raw Juice'), ('clarified_juice', 'Clarified Juice'), ('syrup', 'Syrup'), ('molasses', 'Molasses'), ('raw_sugar', 'Raw Sugar'), ('refined_sugar', 'Refined Sugar'), ('bagasse', 'Bagasse'), ('filter_cake', 'Filter Cake')], max_length=20, verbose_name='output type')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kilograms', max_digits=10, verbose_name='quantity')),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='Quality rating from 1 to 10', null=True, verbose_name='quality rating')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionbatch', verbose_name='production batch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_outputs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'production output',
                'verbose_name_plural': 'production outputs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('pressure', models.DecimalField(decimal_places=2, help_text='Hydraulic pressure in crushing rollers', max_digits=6, verbose_name='pressure (bar)')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Operating temperature', max_digits=5, verbose_name='temperature (°C)')),
                ('rotation_speed', models.DecimalField(decimal_places=2, help_text='Roller rotation speed', max_digits=6, verbose_name='rotation speed (RPM)')),
                ('torque', models.DecimalField(decimal_places=2, help_text='Motor torque', max_digits=8, verbose_name='torque (Nm)')),
                ('vibration', models.DecimalField(decimal_places=2, help_text='Vibration level', max_digits=6, verbose_name='vibration (mm/s)')),
                ('power_consumption', models.DecimalField(decimal_places=2, help_text='Electrical power consumption', max_digits=8, verbose_name='power consumption (kW)')),
                ('feed_rate', models.DecimalField(decimal_places=2, help_text='Sugarcane feed rate', max_digits=6, verbose_name='feed rate (tons/hour)')),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture content in cane', max_digits=5, null=True, verbose_name='moisture content (%)')),
                ('brix_level', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar content in juice', max_digits=5, null=True, verbose_name='brix level (%)')),
                ('extraction_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Juice extraction efficiency', max_digits=5, null=True, verbose_name='extraction rate (%)')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='production.productionbatch', verbose_name='production batch')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='production.crushingmachine', verbose_name='machine')),
            ],
            options={
                'verbose_name': 'sensor reading',
                'verbose_name_plural': 'sensor readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='detected at')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='severity')),
                ('anomaly_score', models.DecimalField(decimal_places=4, help_text='ML model anomaly score', max_digits=6, verbose_name='anomaly score')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20, verbose_name='status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='production.crushingmachine', verbose_name='machine')),
                ('sensor_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='production.sensorreading', verbose_name='sensor reading')),
            ],
            options={
                'verbose_name': 'anomaly alert',
                'verbose_name_plural': 'anomaly alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('current_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='current pressure')),
                ('current_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='current temperature')),
                ('current_rotation_speed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='current rotation speed')),
                ('current_feed_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='current feed rate')),
                ('current_yield', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='current yield')),
                ('recommended_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='recommended pressure')),
                ('recommended_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='recommended temperature')),
                ('recommended_rotation_speed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='recommended rotation speed')),
                ('recommended_feed_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='recommended feed rate')),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='expected yield')),
                ('expected_improvement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='expected improvement (%)')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='ML model confidence (0-100)', max_digits=4, verbose_name='confidence score')),
                ('is_applied', models.BooleanField(default=False, verbose_name='is applied')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied at')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield after applying recommendation', max_digits=8, null=True, verbose_name='actual yield')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='applied by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_recommendations', to='production.crushingmachine', verbose_name='machine')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_recommendations', to='production.productionbatch', verbose_name='production batch')),
            ],
            options={
                'verbose_name': 'optimization recommendation',
                'verbose_name_plural': 'optimization recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['machine', '-created_at'], name='production__machine_b3a075_idx'), models.Index(fields=['is_applied', '-created_at'], name='production__is_appl_9cc8d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_stages', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_stages', to='production.productionbatch', verbose_name='production batch')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_instances', to='production.productionstage', verbose_name='production stage')),
            ],
            options={
                'verbose_name': 'batch stage',
                'verbose_name_plural': 'batch stages',
                'ordering': ['batch', 'start_time'],
                'unique_together': {('batch', 'stage')},
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['machine', '-timestamp'], name='production__machine_e73ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['batch', '-timestamp'], name='production__batch_i_24f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['machine', '-detected_at'], name='production__machine_4da8be_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['status', '-detected_at'], name='production__status_f5b816_idx'),
        ),
    ]
