# Generated by Django 5.2.7 on 2026-03-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='machine name')),
                ('machine_type', models.CharField(choices=[('crusher', 'Crusher'), ('boiler', 'Boiler'), ('evaporator', 'Evaporator'), ('centrifuge', 'Centrifuge'), ('dryer', 'Dryer'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=20, verbose_name='machine type')),
                ('model_number', models.CharField(blank=True, max_length=50, verbose_name='model number')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='serial number')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('installation_date', models.DateField(verbose_name='installation date')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='last maintenance')),
                ('next_maintenance_due', models.DateField(blank=True, null=True, verbose_name='next maintenance due')),
                ('current_status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('error', 'Error'), ('offline', 'Offline')], default='idle', max_length=20, verbose_name='current status')),
                ('efficiency_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100)', max_digits=5, null=True, verbose_name='efficiency rating')),
                ('operating_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='operating hours')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Current temperature in Celsius', max_digits=6, null=True, verbose_name='temperature')),
                ('vibration_level', models.DecimalField(blank=True, decimal_places=2, help_text='Vibration level in Hz', max_digits=6, null=True, verbose_name='vibration level')),
                ('power_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Power consumption in kW', max_digits=8, null=True, verbose_name='power consumption')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='is healthy')),
                ('health_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Overall health score (0-100)', max_digits=5, verbose_name='health score')),
                ('last_health_check', models.DateTimeField(auto_now=True, verbose_name='last health check')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='temperature')),
                ('vibration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='vibration')),
                ('power_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='power consumption')),
                ('production_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='production rate')),
                ('error_code', models.CharField(blank=True, max_length=20, verbose_name='error code')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='is anomaly')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='production.machine')),
            ],
            options={
                'verbose_name': 'Machine Reading',
                'verbose_name_plural': 'Machine Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
