# Generated by Django 5.2.7 on 2025-10-10 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='supplier name')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('payment_terms', models.TextField(blank=True, verbose_name='payment terms')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='abbreviation')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='inventory.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='barcode')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('item_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good'), ('consumable', 'Consumable'), ('equipment', 'Equipment'), ('spare_part', 'Spare Part')], default='raw_material', max_length=20, verbose_name='item type')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum quantity')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum quantity')),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity at which to reorder', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='reorder point')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_serialized', models.BooleanField(default=False, help_text='Whether this item requires serial number tracking', verbose_name='is serialized')),
                ('is_lot_tracked', models.BooleanField(default=False, help_text='Whether this item requires lot/batch tracking', verbose_name='is lot tracked')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category', verbose_name='category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unitofmeasure', verbose_name='unit of measure')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='location code')),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('shelf', 'Shelf'), ('bin', 'Bin'), ('room', 'Room'), ('area', 'Area')], default='shelf', max_length=20, verbose_name='location type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of items that can be stored in this location', null=True, verbose_name='maximum capacity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublocations', to='inventory.location', verbose_name='parent location')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('consumption', 'Consumption'), ('return', 'Return'), ('scrap', 'Scrap')], max_length=20, verbose_name='transaction type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='unit cost')),
                ('reference', models.CharField(blank=True, help_text='Reference number or document number', max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.item', verbose_name='item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'inventory transaction',
                'verbose_name_plural': 'inventory transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type'], name='inventory_i_transac_2eccee_idx'), models.Index(fields=['reference'], name='inventory_i_referen_6e561a_idx'), models.Index(fields=['created_at'], name='inventory_i_created_670884_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='serial number')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='lot/batch number')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('manufactured_date', models.DateField(blank=True, null=True, verbose_name='manufactured date')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.item', verbose_name='item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.location', verbose_name='location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['item__name', 'lot_number', 'serial_number'],
                'indexes': [models.Index(fields=['serial_number'], name='inventory_i_serial__203210_idx'), models.Index(fields=['lot_number'], name='inventory_i_lot_num_002f8b_idx'), models.Index(fields=['expiry_date'], name='inventory_i_expiry__69d012_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('item', 'serial_number'), name='unique_item_serial')],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='inventory_i_sku_3e99d5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type'], name='inventory_i_item_ty_3448a3_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_fd4174_idx'),
        ),
    ]
