# Generated by Django 5.2.7 on 2025-10-15 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='farm name')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='area (acres)')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=20, verbose_name='soil type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_acquired', models.DateField(auto_now_add=True, verbose_name='date acquired')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('plowing', 'Plowing'), ('planting', 'Planting'), ('fertilizing', 'Fertilizing'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('harvesting', 'Harvesting'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20, verbose_name='activity type')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(verbose_name='description')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.farm')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm activity',
                'verbose_name_plural': 'farm activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmCropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100, verbose_name='sugarcane variety')),
                ('planting_date', models.DateField(verbose_name='planting date')),
                ('expected_harvest_date', models.DateField(verbose_name='expected harvest date')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='actual harvest date')),
                ('current_stage', models.CharField(choices=[('preparation', 'Land Preparation'), ('planting', 'Planting'), ('growing', 'Growing'), ('mature', 'Mature'), ('harvested', 'Harvested'), ('fallow', 'Fallow')], default='preparation', max_length=20, verbose_name='current stage')),
                ('estimated_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated yield (tons)')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='actual yield (tons)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='farms.farm')),
            ],
            options={
                'verbose_name': 'crop cycle',
                'verbose_name_plural': 'crop cycles',
                'ordering': ['-planting_date'],
            },
        ),
    ]
