# Generated by Django 5.2.7 on 2026-03-16 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='mobile number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='village')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='district')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('pin_code', models.CharField(blank=True, max_length=10, verbose_name='PIN code')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='bank account number')),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='bank IFSC code')),
                ('bank_branch', models.CharField(blank=True, max_length=200, verbose_name='bank branch')),
                ('total_land_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total land area in acres', max_digits=10, null=True, verbose_name='total land area (acres)')),
                ('land_holding_type', models.CharField(blank=True, help_text='e.g., Owned, Leased, Shared', max_length=100, verbose_name='land holding type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-registration_date'],
            },
        ),
    ]
